name: HTML Lint Check

on:
    push:
        branches:
            - main

jobs:
    html-lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install HTML-Validate
              run: npm install -g html-validate

            - name: Run HTML-Validate
              run: html-validate "**/*.html"